name: CMake Build
inputs:
  build-dir:
    required: true
    default: build
  build-type:
    required: true
    default: Release
  shell:
    required: true
    default: bash
  target:
    required: false
runs:
  using: "composite"
  steps:
    - name: Build
      run: |
        if [[ ! -z "${{ inputs.target }}" ]]; then
          cmake_args+=(--target "${{ inputs.target }}")
        fi
        cmake --build "${{ inputs.build-dir }}" --config "${{ inputs.build-type }}" "${cmake_args[@]}"
      shell: ${{ inputs.shell }}
