name: CMake Install
inputs:
  build-dir:
    required: true
    default: build
  build-type:
    required: true
    default: Release
  shell:
    required: true
    default: bash
  install-wrapper-cmd:
    required: false
runs:
  using: "composite"
  steps:
    - name: Install
      run: |
        if [[ ! -z "${{ inputs.install-wrapper-cmd }}" ]]; then
          wrapper_cmd+=("${{ inputs.install-wrapper-cmd }}")
        fi
        "${wrapper_cmd[@]}" cmake --install "${{ inputs.build-dir }}" --config "${{ inputs.build-type }}"
      shell: ${{ inputs.shell }}
