name: Sign artifacts
description: Sign artifacts
inputs:
  directory:
    description: Artifact directory
    required: true
runs:
  using: composite
  steps:
    - name: Create checksum file
      run: sha256sum * > SHA256SUMS
      working-directory: ${{ inputs.directory }}
      shell: bash

    - name: Sign artifacts
      run: gpg --batch --pinentry-mode loopback --detach-sign --armor SHA256SUMS
      working-directory: ${{ inputs.directory }}
      shell: bash
