set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER g++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_RANLIB ranlib)
set(CMAKE_RC_COMPILER windres)

set(MSYSTEM ucrt64)
