name: CI / Check
on:
  workflow_call:
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --no-install-recommends -y clang-format-15
      - run: CLANG_FORMAT_EXE=clang-format-15 ./scripts/check_format.sh

  lint-linux:
    name: lint-linux (c++${{ matrix.cxx-std }}, webkitgtk${{ matrix.webkitgtk-api }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx-std: [11, 14, 17, 20]
        webkitgtk-api: ['4.0', '4.1', '6.0']
        include:
          - webkitgtk-api: '4.0'
            apt-webkitgtk: libgtk-3-dev libwebkit2gtk-4.0-dev
          - webkitgtk-api: '4.1'
            apt-webkitgtk: libgtk-3-dev libwebkit2gtk-4.1-dev
          - webkitgtk-api: '6.0'
            apt-webkitgtk: libgtk-4-dev libwebkitgtk-6.0-dev
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --no-install-recommends -y cmake ninja-build clang-15 clang-tidy-15 ${{ matrix.apt-webkitgtk }}
      - run: >
          cmake
          -G Ninja
          -B build
          -S .
          -D CMAKE_C_COMPILER=clang
          -D CMAKE_CXX_COMPILER=clang++
          -D "CMAKE_CXX_STANDARD=${{ matrix.cxx-std }}"
          -D CMAKE_C_CLANG_TIDY=clang-tidy-15
          -D CMAKE_CXX_CLANG_TIDY=clang-tidy-15
