name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  check:
    uses: ./.github/workflows/check.yaml

  build:
    needs: check
    uses: ./.github/workflows/build.yaml

  build-pr:
    if: github.event_name == 'pull_request'
    needs: check
    uses: ./.github/workflows/build.yaml
    with:
      pr: true
