name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
#  check:
#    uses: ./.github/workflows/check.yml

#  test:
#    needs: check
#    uses: ./.github/workflows/test.yml

  package:
#    needs: test
    uses: ./.github/workflows/package.yml
