name: CMake
on: [push, pull_request]

jobs:
  cmake-linux:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        generator: [Ninja]
        image: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake lcov libwebkit2gtk-4.0-dev ninja-build xvfb -y
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          configure: true
          build: true
          test: true
          install: true
          package: true
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          test-wrapper-cmd: xvfb-run
          install-wrapper-cmd: sudo

  cmake-linux-mingw-w64:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [14, 17, 20]
        generator: [Ninja]
        image: [ubuntu-20.04, ubuntu-22.04]
        exclude:
          - cxx-std: 20
            image: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake mingw-w64 ninja-build -y
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          configure: true
          build: true
          test: false
          install: false
          package: true
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          toolchain-file: x86_64-w64-mingw32

  cmake-macos:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        generator: [Xcode]
        image: [macos-11, macos-12]
        architectures: [arm64, x86_64, arm64;x86_64]
        include:
          - test: true
            install: true
          - architectures: arm64
            test: false
            install: false
    steps:
      - name: Install dependencies
        run: brew install lcov
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          configure: true
          build: true
          test: ${{ matrix.test }}
          install: ${{ matrix.install }}
          package: true
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
          install-wrapper-cmd: sudo
          macos-architectures: ${{ matrix.architectures }}
          upload-artifacts: ${{ matrix.build-type == 'Release' && matrix.cxx-std == 20 && matrix.generator == 'Xcode' && matrix.image == 'macos-12' }}
          artifact-name: ${{ github.job }}_${{ matrix.image }}_${{ matrix.generator }}_cxx${{ matrix.cxx-std }}_${{ matrix.build-type }}_${{ matrix.architectures }}

  cmake-windows-msys2:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        msystem: [mingw64] #[clang64, mingw64, ucrt64]
        generator: [Ninja]
        image: [windows-2022]
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: false
          pacboy: toolchain:p cmake:p lcov:p ninja:p
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          configure: true
          build: true
          test: true
          install: true
          package: true
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          shell: msys2 {0}
          upload-artifacts: ${{ matrix.build-type == 'Release' && matrix.cxx-std == 20 && matrix.generator == 'Ninja' && matrix.image == 'windows-2022' }}
          artifact-name: ${{ github.job }}_${{ matrix.image }}_${{ matrix.generator }}_cxx${{ matrix.cxx-std }}_${{ matrix.build-type }}_${{ matrix.msystem }}

  cmake-windows-msvc:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        cxx-std: [14, 17, 20]
        generator-platform: [ARM64, x64, Win32]
        image: [windows-2022]
        include:
          - test: true
            install: true
          - image: windows-2022
            generator: Visual Studio 17 2022
          - generator-platform: ARM64
            test: false
            install: false
          - generator: Visual Studio 17 2022
            generator-short-name: vs17
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        uses: ./.github/workflows/cmake
        with:
          configure: true
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
      - name: Build Debug
        uses: ./.github/workflows/cmake
        with:
          build: true
          test: ${{ matrix.test }}
          build-type: Debug
      - name: Build Release
        uses: ./.github/workflows/cmake
        with:
          build: true
          test: ${{ matrix.test }}
          build-type: Release
      - name: Package
        uses: ./.github/workflows/cmake
        with:
          install: ${{ matrix.install }}
          package: true
          package-configurations: Debug;Release
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
          upload-artifacts: ${{ matrix.cxx-std == 20 && matrix.generator == 'Visual Studio 17 2022' && matrix.image == 'windows-2022' }}
          artifact-name: ${{ github.job }}_${{ matrix.image }}_${{ matrix.generator-short-name }}_cxx${{ matrix.cxx-std }}_${{ matrix.generator-platform }}

  swig:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        language: [csharp, java, python, ruby]
    steps:
      - uses: actions/checkout@v3
      - name: Generate bindings with SWIG
        run: |
          mkdir -p "build/bindings/${{ matrix.language }}" \
            && swig -Wall -Werror -c++ "-${{ matrix.language }}" \
              -outdir "build/bindings/${{ matrix.language }}" \
              -o build/bindings/${{ matrix.language }}/${{ matrix.language }}_wrap.cpp \
              webview.i

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
