name: CI Pipeline
on: [push, pull_request]

jobs:
  lint:
    name: lint (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        # macOS was excluded because clang-tidy is not installed.
        include:
          - os: linux
            image: ubuntu-latest
            arch: x64
          - os: windows
            image: windows-latest
            arch: x64
          - os: windows
            image: windows-latest
            arch: x86
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Run lint checks
        run: python3 script/build.py --check-style --check-lint=lax "--target-arch=${{ matrix.arch }}"

  build-linux:
    name: build (linux, ${{ matrix.arch }}, ${{ matrix.compiler.id }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        compiler:
          - { id: gcc, ar: ar, cc: gcc, cxx: g++, ld: ld }
          - { id: clang, ar: ar, cc: clang, cxx: clang++, ld: ld }
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13'
      - name: Build and run tests
        run: xvfb-run python3 script/build.py "--ar=${{ matrix.compiler.ar }}" "--cc=${{ matrix.compiler.cc }}" "--cxx=${{ matrix.compiler.cxx }}" "--ld=${{ matrix.compiler.ld }}" --build-examples --test
      - name: Build Go examples and run Go tests
        run: xvfb-run python3 script/build.py "--ar=${{ matrix.compiler.ar }}" "--cc=${{ matrix.compiler.cc }}" "--cxx=${{ matrix.compiler.cxx }}" "--ld=${{ matrix.compiler.ld }}" --go-build-examples --go-test

  build-macos:
    name: build (macos)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13'
      - name: Build and run tests
        run: python3 script/build.py --build-examples --test --go-test

  build-windows:
    name: build (windows, ${{ matrix.arch }}, ${{ matrix.compiler.id }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        compiler:
          - { id: msvc, toolchain: msvc, ar: lib, cc: cl, cxx: cl, ld: link }
          - { id: mingw-gcc, toolchain: mingw, ar: ar, cc: gcc, cxx: g++, ld: ld }
          - { id: mingw-clang, toolchain: mingw, ar: llvm-ar, cc: clang, cxx: clang++, ld: ld.lld }
        include:
          - arch: x64
            compiler: { toolchain: mingw }
            mingw_url: https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-10.0.0-msvcrt-r2/winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-14.0.6-mingw-w64msvcrt-10.0.0-r2.zip
            mingw_hash: 290fc7b0d531eb4ea54640007f3e20b360580b6d2189d08d39907cb9a3df114a
          - arch: x86
            compiler: { toolchain: mingw }
            mingw_url: https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-10.0.0-msvcrt-r2/winlibs-i686-posix-dwarf-gcc-12.2.0-llvm-14.0.6-mingw-w64msvcrt-10.0.0-r2.zip
            mingw_hash: 187b68dd034a74a951b110f7d0253a3667cf191a4fb2e79bcacf856ae09aa75e
    steps:
      - uses: actions/checkout@v3
      - name: Disable existing MinGW-w64 (Chocolatey)
        run: |
          if (Test-Path -Path "${env:ProgramData}\chocolatey\lib\mingw") {
            Rename-Item -Path "${env:ProgramData}\chocolatey\lib\mingw" -NewName "mingw.disabled" -Force
          }
      # The MinGW-w64 distribution from https://winlibs.com/ is known to have good compatibility
      # with the webview library.
      # Distribution: GCC 12.2.0 + MinGW-w64 10.0.0 (MSVCRT) - release 2
      # The MSVCRT runtime was chosen over UCRT because MSVCRT is available on old versions of Windows
      # while UCRT has only been shipped with Windows since Windows 10.
      - name: Install MinGW-w64
        if: matrix.compiler.toolchain == 'mingw'
        run: |
          $ProgressPreference = "SilentlyContinue"
          $temp_dir = [System.IO.Path]::GetTempPath()
          $zip_path = Join-Path $temp_dir ([System.IO.Path]::GetRandomFileName() + ".zip")
          Invoke-WebRequest -Uri "${{ matrix.mingw_url }}" -OutFile $zip_path
          Expand-Archive -LiteralPath $zip_path -DestinationPath "${env:SystemDrive}\"
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13'
      - name: Build and run tests
        run: python3 script/build.py "--target-arch=${{ matrix.arch }}" "--load-toolchain=${{ matrix.compiler.toolchain }}" "--ar=${{ matrix.compiler.ar }}" "--cc=${{ matrix.compiler.cc }}" "--cxx=${{ matrix.compiler.cxx }}" "--ld=${{ matrix.compiler.ld }}" --build-examples --test
        shell: cmd
      - name: Build Go examples and run Go tests
        if: matrix.compiler.toolchain == 'mingw'
        run: python3 script/build.py "--target-arch=${{ matrix.arch }}" "--load-toolchain=${{ matrix.compiler.toolchain }}" "--ar=${{ matrix.compiler.ar }}" "--cc=${{ matrix.compiler.cc }}" "--cxx=${{ matrix.compiler.cxx }}" "--ld=${{ matrix.compiler.ld }}" --go-build-examples --go-test
        shell: cmd

  swig:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [csharp, java, python, ruby]
    steps:
      - uses: actions/checkout@v1
      - name: Generate bindings with SWIG
        run: |
          mkdir -p "build/bindings/${{ matrix.language }}" \
            && swig -Wall -Werror -c++ "-${{ matrix.language }}" \
              -outdir "build/bindings/${{ matrix.language }}" \
              -o build/bindings/${{ matrix.language }}/${{ matrix.language }}_wrap.cpp \
              webview.i

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
