name: CI Pipeline
on: [push, pull_request]

jobs:
  go-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - run: go build

  go-matrix:
    strategy:
      matrix:
        tag: [cxx11, cxx14, cxx17, cxx20, cxx23]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - run: go build --tags "${{ matrix.tag }}"
