name: CMake
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: '.'
          exclude: './build'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file

  cmake-main-linux:
    name: cmake-main (${{ matrix.image }}, linux, ${{ matrix.cc }}, c++${{ matrix.standard }})
    needs: checks
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu-22.04
            cc: clang-15
            cxx: clang++-15
            gcov: llvm-cov-15 gcov
            standard: 11
            test-coverage: true
            apt-packages: clang-15
          - image: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            gcov: gcov-12
            standard: 11
            test-coverage: false
            apt-packages: gcc-12 g++-12
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          gcov: ${{ matrix.gcov }}
          standard: ${{ matrix.standard }}
          generator: Ninja
          test-coverage: ${{ matrix.test-coverage }}
          test-coverage-name: main_linux_${{ matrix.cc }}_cxx${{ matrix.standard }}
          test-wrapper-cmd: xvfb-run
          apt-packages: ${{ matrix.apt-packages }}
          install-wrapper-cmd: sudo

  cmake-main-linux-mingw-w64:
    name: cmake-main (${{ matrix.image }}, win, ${{ matrix.toolchain-file }}, c++${{ matrix.standard }})
    needs: checks
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu-22.04
            toolchain-file: x86_64-w64-mingw32
            standard: 14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          toolchain-file: ${{ github.workspace }}/cmake/toolchains/${{ matrix.toolchain-file }}.cmake
          standard: ${{ matrix.standard }}
          generator: Ninja
          test: false
          apt-packages: mingw-w64
          install-wrapper-cmd: sudo

  cmake-main-macos:
    name: cmake-main (${{ matrix.image }}, macos, c++${{ matrix.standard }}, ${{ matrix.osx-architectures }})
    needs: checks
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: macos-12
            standard: 11
            test-coverage: true
            osx-architectures: x86_64
            distributable: false
          - image: macos-12
            standard: 11
            # While we can get coverage for universal binaries, keep it simple by
            # avoiding the need to specify the architecture to get coverage for.
            test-coverage: false
            osx-architectures: arm64;x86_64
            distributable: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: clang
          cxx: clang++
          standard: ${{ matrix.standard }}
          generator: Xcode
          test-coverage: ${{ matrix.test-coverage }}
          test-coverage-name: main_macos_cxx${{ matrix.standard }}
          osx-architectures: ${{ matrix.osx-architectures }}
          install-wrapper-cmd: sudo
          distributable: ${{ matrix.distributable }}

  cmake-main-windows-msys2:
    name: cmake-main (${{ matrix.image }}, win, msys2, ${{ matrix.msys2-system }}, ${{ matrix.cc }}, c++${{ matrix.standard }})
    needs: checks
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: windows-2022
            cc: clang
            cxx: clang++
            standard: 14
            test-coverage: true
            msys2-system: CLANG64
          - image: windows-2022
            cc: gcc
            cxx: g++
            standard: 14
            test-coverage: false
            msys2-system: UCRT64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          standard: ${{ matrix.standard }}
          generator: MSYS Makefiles
          test-coverage: ${{ matrix.test-coverage }}
          test-coverage-name: main_win_msys2_${{ matrix.msys2-system }}_${{ matrix.cc }}_cxx${{ matrix.standard }}
          msys2-system: ${{ matrix.msys2-system }}
          shell: msys2 {0}

  cmake-main-windows-msvc:
    name: cmake-main (${{ matrix.image }}, win, msvc, c++${{ matrix.standard }}, ${{ matrix.generator-platform }})
    needs: checks
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: windows-2022
            standard: 14
            generator: Visual Studio 17 2022
            generator-platform: ARM64
            # Skip tests because we can't execute ARM64 binaries
            test: false
          - image: windows-2022
            standard: 14
            generator: Visual Studio 17 2022
            generator-platform: x64
            test: true
          - image: windows-2022
            standard: 14
            generator: Visual Studio 17 2022
            generator-platform: Win32
            test: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          build-type: Debug;Release
          cc: cl
          cxx: cl
          standard: ${{ matrix.standard }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
          test: ${{ matrix.test }}
          test-coverage: false
          distributable: true

  cmake-main:
    runs-on: ubuntu-latest
    needs:
      - cmake-main-linux
      - cmake-main-linux-mingw-w64
      - cmake-main-macos
      - cmake-main-windows-msys2
      - cmake-main-windows-msvc
    steps:
      - run: echo

  cmake-extra-linux:
    name: cmake-extra (${{ matrix.image }}, linux, ${{ matrix.cc }}, c++${{ matrix.standard }})
    needs: cmake-main
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
            gcov: llvm-cov-8 gcov
            standard: 11
            apt-packages: clang-8
          - image: ubuntu-22.04
            cc: clang-15
            cxx: clang++-15
            gcov: llvm-cov-15 gcov
            standard: 14
            apt-packages: clang-15
          - image: ubuntu-22.04
            cc: clang-15
            cxx: clang++-15
            gcov: llvm-cov-15 gcov
            standard: 17
            apt-packages: clang-15
          - image: ubuntu-22.04
            cc: clang-15
            cxx: clang++-15
            gcov: llvm-cov-15 gcov
            standard: 20
            apt-packages: clang-15
          - image: ubuntu-20.04
            cc: gcc-7
            cxx: g++-7
            gcov: gcov-7
            standard: 11
            apt-packages: gcc-7 g++-7
          - image: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            gcov: gcov-12
            standard: 14
            apt-packages: gcc-12 g++-12
          - image: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            gcov: gcov-12
            standard: 17
            apt-packages: gcc-12 g++-12
          - image: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            gcov: gcov-12
            standard: 20
            apt-packages: gcc-12 g++-12
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          gcov: ${{ matrix.gcov }}
          standard: ${{ matrix.standard }}
          generator: Ninja
          test-coverage: false
          test-wrapper-cmd: xvfb-run
          apt-packages: ${{ matrix.apt-packages }}
          install-wrapper-cmd: sudo

  cmake-extra-linux-mingw-w64:
    name: cmake-extra (${{ matrix.image }}, win, ${{ matrix.toolchain-file }}, c++${{ matrix.standard }})
    needs: cmake-main
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu-22.04
            toolchain-file: i686-w64-mingw32
            standard: 14
          - image: ubuntu-22.04
            toolchain-file: x86_64-w64-mingw32
            standard: 17
          - image: ubuntu-22.04
            toolchain-file: x86_64-w64-mingw32
            standard: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          toolchain-file: ${{ github.workspace }}/cmake/toolchains/${{ matrix.toolchain-file }}.cmake
          standard: ${{ matrix.standard }}
          generator: Ninja
          test: false
          apt-packages: mingw-w64
          install-wrapper-cmd: sudo

  cmake-extra-macos:
    name: cmake-extra (${{ matrix.image }}, macos, c++${{ matrix.standard }})
    needs: cmake-main
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: macos-11
            standard: 11
          - image: macos-12
            standard: 14
          - image: macos-12
            standard: 17
          - image: macos-12
            standard: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: clang
          cxx: clang++
          standard: ${{ matrix.standard }}
          generator: Xcode
          test-coverage: false
          install-wrapper-cmd: sudo

  cmake-extra-windows-msys2:
    name: cmake-extra (${{ matrix.msys2-system }}, ${{ matrix.image }}, win, msys2, ${{ matrix.cc }}, c++${{ matrix.standard }})
    needs: cmake-main
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          # "MSYS" environment skipped due to error "pacman: unknown option -- a"
          # "CLANGARM64" environment skipped due to error "/clangarm64/bin/cmake: cannot execute binary file: Exec format error"
          - image: windows-2022
            cc: clang
            cxx: clang++
            standard: 17
            msys2-system: CLANG64
          - image: windows-2022
            cc: clang
            cxx: clang++
            standard: 20
            msys2-system: CLANG64
          - image: windows-2022
            cc: clang
            cxx: clang++
            standard: 14
            msys2-system: CLANG32
          - image: windows-2022
            cc: gcc
            cxx: g++
            standard: 14
            msys2-system: MINGW64
          - image: windows-2022
            cc: gcc
            cxx: g++
            standard: 14
            msys2-system: MINGW32
          - image: windows-2022
            cc: gcc
            cxx: g++
            standard: 17
            msys2-system: UCRT64
          - image: windows-2022
            cc: gcc
            cxx: g++
            standard: 20
            msys2-system: UCRT64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          standard: ${{ matrix.standard }}
          generator: MSYS Makefiles
          test-coverage: false
          msys2-system: ${{ matrix.msys2-system }}
          shell: msys2 {0}

  cmake-extra-windows-msvc:
    name: cmake-extra (${{ matrix.image }}, win, msvc, c++${{ matrix.standard }}, ${{ matrix.generator-platform }})
    needs: cmake-main
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: windows-2019
            standard: 14
            generator: Visual Studio 16 2019
            generator-platform: x64
            # Skip tests because WebView2 Runtime isn't installed
            test: false
          - image: windows-2022
            standard: 17
            generator: Visual Studio 17 2022
            generator-platform: x64
            test: true
          - image: windows-2022
            standard: 20
            generator: Visual Studio 17 2022
            generator-platform: x64
            test: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cmake
        with:
          cc: cl
          cxx: cl
          standard: ${{ matrix.standard }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
          test: ${{ matrix.test }}
          test-coverage: false

  cmake-extra:
    needs:
      - cmake-extra-linux
      - cmake-extra-linux-mingw-w64
      - cmake-extra-macos
      - cmake-extra-windows-msys2
      - cmake-extra-windows-msvc
    runs-on: ubuntu-latest
    steps:
      - run: echo

  test-coverage:
    needs: cmake-extra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: ./.github/workflows/coverage

  doxygen:
    needs: cmake-extra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen -y
      - run: mkdir -p build/docs
      - name: Run Doxygen
        run: doxygen

  swig:
    needs: cmake-extra
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [csharp, java, python, ruby]
    steps:
      - uses: actions/checkout@v4
      - name: Generate bindings with SWIG
        run: |
          mkdir -p "build/bindings/${{ matrix.language }}" \
            && swig -Wall -Werror -c++ "-${{ matrix.language }}" \
              -outdir "build/bindings/${{ matrix.language }}" \
              -o build/bindings/${{ matrix.language }}/${{ matrix.language }}_wrap.cpp \
              webview.i
