name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    if: false
    name: build (${{ matrix.system.name }}, ${{ matrix.arch }}, ${{ matrix.compiler.id }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - name: linux
          image: ubuntu-latest
          compiler:
            - { id: gcc, ar: ar, cc: gcc, cxx: g++, ld: ld }
            - { id: clang, ar: ar, cc: clang, cxx: clang++, ld: ld }
        - name: macos
          image: macos-latest
          compiler:
            - { id: clang, ar: ar, cc: clang, cxx: clang++, ld: ld }
        - name: windows
          image: windows-latest
          compiler:
            - { id: msvc, ar: lib, cc: cl, cxx: cl, ld: link }
            - { id: gcc, ar: ar, cc: gcc, cxx: g++, ld: ld }
            - { id: clang, ar: llvm-ar, cc: clang, cxx: clang++, ld: ld.lld }
        include:
          - arch: x64
          - name: windows
            arch: [arm64, x86]
            compiler:
              id: msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (${{ matrix.system.name }})
        if: matrix.system.name == 'linux'
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Build and run tests (${{ matrix.system.name }})
        run: xvfb-run python3 script/build.py "--ar=${{ matrix.compiler.ar }}" "--cc=${{ matrix.compiler.cc }}" "--cxx=${{ matrix.compiler.cxx }}" "--ld=${{ matrix.compiler.ld }}" --build-examples --test
