name: CI Pipeline
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Build and run tests
        run: xvfb-run ./script/build.sh --reformat --lint=lax --build-examples --test --go-test

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        # clang-format and clang-tidy are not installed.
        run: ./script/build.sh --build-examples --test --go-test

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: script\build.bat --reformat --lint=lax --target-arch=${{ matrix.arch }} --build-examples --test
        shell: cmd
      - name: Run Go tests
        if: matrix.arch == 'x64'
        run: script\build.bat --go-test
        shell: cmd

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
