name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    name: build-${{ matrix.config.os-family }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            os-family: linux
            run-cmd: xvfb-run
            deps-cmd: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
            test-timeout: 10
            cc: 'gcc'
            cxx: 'g++'
          - os: macos-latest
            os-family: macos
            run-cmd: ''
            deps-cmd: ''
            test-timeout: 10
            compiler: 'clang'
            cc: 'clang'
            cxx: 'clang++'
          - os: windows-latest
            os-family: windows
            run-cmd: ''
            deps-cmd: 'choco install mingw'
            test-timeout: 60
            cc: 'gcc'
            cxx: 'g++'
          - os: windows-latest
            os-family: windows
            run-cmd: ''
            deps-cmd: 'choco install mingw'
            test-timeout: 60
            cc: 'cl'
            cxx: 'cl'
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.config.deps-cmd != ''
        run: ${{ matrix.config.deps-cmd }}
      - name: Build and test
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: >
          ${{ matrix.config.run-cmd }} python3 script/dev.py clean configure
          --examples --tests build test --timeout=${{ matrix.config.test-timeout }}
          go:build go:test

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
