name: CI Pipeline
on: [push, pull_request]

jobs:
  cmake-linux:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        generator: [Ninja]
        image: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake libwebkit2gtk-4.0-dev ninja-build xvfb -y
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          build-type: ${{ matrix.build-type }}
          generator: ${{ matrix.generator }}
          install-wrapper-cmd: sudo
          test-wrapper-cmd: xvfb-run

  cmake-linux-mingw-w64:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [14, 17, 20]
        generator: [Ninja]
        image: [ubuntu-20.04, ubuntu-22.04]
        exclude:
          - cxx-std: 20
            image: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake mingw-w64 ninja-build -y
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          build-type: ${{ matrix.build-type }}
          generator: ${{ matrix.generator }}
          test: false
          install: false
          toolchain-file: x86_64-w64-mingw32

  cmake-macos:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        generator: [Xcode]
        image: [macos-11, macos-12, macos-13]
        architectures: [arm64, x86_64, arm64;x86_64]
        include:
          - architectures: arm64
            test: false
    steps:
      - name: Install dependencies
        run: brew install cmake ninja
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          install-wrapper-cmd: sudo
          generator: ${{ matrix.generator }}
          macos-architectures: ${{ matrix.architectures }}
          test: ${{ matrix.test }}

  cmake-windows-msys2:
    runs-on: windows-2022
    strategy:
      matrix:
        build-type: [Release]
        cxx-std: [11, 14, 17, 20]
        msystem: [clang64, mingw64, ucrt64]
        generator: [Ninja]
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: false
          pacboy: toolchain:p cmake:p ninja:p
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          shell: msys2 {0}

  cmake-windows-msvc:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        build-type: [Debug, Release]
        cxx-std: [14, 17, 20]
        generator-platform: [ARM64, x64, Win32]
        image: [windows-2022]
        include:
          - image: windows-2022
            generator: Visual Studio 17 2022
          - generator-platform: ARM64
            test: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cmake
        with:
          build-type: ${{ matrix.build-type }}
          cxx-std: ${{ matrix.cxx-std }}
          generator: ${{ matrix.generator }}
          generator-platform: ${{ matrix.generator-platform }}
          test: ${{ matrix.test }}

  swig:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        language: [csharp, java, python, ruby]
    steps:
      - uses: actions/checkout@v3
      - name: Generate bindings with SWIG
        run: |
          mkdir -p "build/bindings/${{ matrix.language }}" \
            && swig -Wall -Werror -c++ "-${{ matrix.language }}" \
              -outdir "build/bindings/${{ matrix.language }}" \
              -o build/bindings/${{ matrix.language }}/${{ matrix.language }}_wrap.cpp \
              webview.i

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
