name: CI Pipeline
on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macOS was excluded because clang-tidy is not installed.
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: x64
            os: windows-latest
          - arch: x86
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Run lint checks
        if: runner.os == 'Windows'
        run: script\build.bat --lint=lax --target-arch=${{ matrix.arch }}
        shell: cmd
      - name: Run lint checks
        if: runner.os != 'Windows'
        run: script/build.sh --lint=lax --target-arch=${{ matrix.arch }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Build and run tests
        run: xvfb-run ./script/build.sh --build-examples --test --go-test

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: ./script/build.sh --build-examples --test --go-test

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: script\build.bat --target-arch=${{ matrix.arch }} --build-examples --test
        shell: cmd
      - name: Run Go tests
        if: matrix.arch == 'x64'
        run: script\build.bat --go-test
        shell: cmd

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './script'
          extensions: 'h,cc'
          clangFormatVersion: 9
          style: file
