name: CI / Build
on:
  workflow_call:
    inputs:
      gcovr-version:
        type: string
        description: gcovr version
        required: false
        default: '7.2'
jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx-std: [20]
        webkitgtk-api: ['4.0', '4.1', '6.0']
        include:
          # Defaults
          - distributable: false
            gen: Ninja
          # Compilers
          - toolchain: llvm
            compiler-name: clang15
            cc: clang-15
            cxx: clang++-15
            apt: clang-15 clang++-15
          - toolchain: gnu
            compiler-name: gcc12
            cc: gcc-12
            cxx: g++-12
            apt: gcc-12 g++-12
          # WebKitGTK
          - webkitgtk-api: '4.0'
            apt-webkitgtk: libgtk-3-dev libwebkit2gtk-4.0-dev
          - webkitgtk-api: '4.1'
            apt-webkitgtk: libgtk-3-dev libwebkit2gtk-4.1-dev
          - webkitgtk-api: '6.0'
            apt-webkitgtk: libgtk-4-dev libwebkitgtk-6.0-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/workflows/setup-env
        with:
          apt: ${{ matrix.apt }} ${{ matrix.apt-webkitgtk }}

      - name: Set up variables
        id: vars
        run: |
          echo "artifacts-name=${{ runner.os }}_${{ matrix.toolchain }}_${{ matrix.compiler-name }}_cxx${{ matrix.cxx-std }}_webkitgtk${{ matrix.webkitgtk-api }}" >> "${GITHUB_OUTPUT}"
          echo "build-config=Release" >> "${GITHUB_OUTPUT}"
          echo "build-dir=build" >> "${GITHUB_OUTPUT}"
          echo "generator=Ninja" >> "${GITHUB_OUTPUT}"
          echo "source-dir=." >> "${GITHUB_OUTPUT}"
          echo "test-wrapper-cmd=xvfb-run" >> "${GITHUB_OUTPUT}"

      - name: Configure
        run: >
          cmake
          -G "${{ steps.vars.outputs.generator }}"
          -B "${{ steps.vars.outputs.build-dir }}"
          -S "${{ steps.vars.outputs.source-dir }}"
          -D "CMAKE_BUILD_TYPE=${{ steps.vars.outputs.build-config }}"
          -D "CMAKE_C_COMPILER=${{ matrix.cc }}"
          -D "CMAKE_CXX_COMPILER=${{ matrix.cxx }}"
          -D "CMAKE_CXX_STANDARD=${{ matrix.cxx-std }}"

      - name: Build
        run: >
          cmake
          --build "${{ steps.vars.outputs.build-dir }}"
          --config "${{ steps.vars.outputs.build-config }}"

      - name: Test
        run: >
          ${{ steps.vars.outputs.test-wrapper-cmd }}
          ctest
          --output-on-failure
          --build-config "${{ steps.vars.outputs.build-config }}"
        working-directory: ${{ steps.vars.outputs.build-dir }}
