name: CI / Package
on:
  workflow_call:
jobs:
  package:
    name: ${{ matrix.os }} (c++${{ matrix.cxx-std }}, ${{ matrix.a }}, ${{ matrix.t }}${{ matrix.tes }}${{ matrix.name-suffix }})
    runs-on: ${{ matrix.i }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # os:      Target operating systme
          # a:       Architecture
          # i:       Image
          # cxx-std: C++ standard
          # g:       CMake generator
          # msvc-mt: Use static MSVC runtime library
          # t:       Toolchain
          # tes:     Toolchain executable suffix
          # sh:      Shell
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: gnu,                tes: '-12',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk6.0', checks: false, test-wrapper-cmd: xvfb-run, apt: gcc-12 g++-12,                     webkitgtk-api: '6.0', docs: true, package-source: true }
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: gnu,                tes: '-12',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.1', checks: false, test-wrapper-cmd: xvfb-run, apt: gcc-12 g++-12,                     webkitgtk-api: '4.1' }
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: gnu,                tes: '-12',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.0', checks: false, test-wrapper-cmd: xvfb-run, apt: gcc-12 g++-12,                     webkitgtk-api: '4.0' }
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: llvm,               tes: '-15',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk6.0', checks: true,  test-wrapper-cmd: xvfb-run, apt: clang-15 clang++-15 clang-tidy-15, webkitgtk-api: '6.0' }
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: llvm,               tes: '-15',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.1', checks: true,  test-wrapper-cmd: xvfb-run, apt: clang-15 clang++-15 clang-tidy-15, webkitgtk-api: '4.1' }
          - { os: linux,   i: ubuntu-22.04, cxx-std: 20, a: host,      t: llvm,               tes: '-15',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.0', checks: true,  test-wrapper-cmd: xvfb-run, apt: clang-15 clang++-15 clang-tidy-15, webkitgtk-api: '4.0' }
          - { os: linux,   i: ubuntu-20.04, cxx-std: 20, a: host,      t: gnu,                tes: '-10',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.0', checks: false, test-wrapper-cmd: xvfb-run, apt: gcc-10 g++-10,                     webkitgtk-api: '4.0' }
          - { os: linux,   i: ubuntu-20.04, cxx-std: 20, a: host,      t: llvm,               tes: '-12',    g: Ninja Multi-Config,    sh: bash,        name-suffix: ', webkitgtk4.0', checks: true,  test-wrapper-cmd: xvfb-run, apt: clang-12 clang++-12 clang-tidy-12, webkitgtk-api: '4.0' }
          - { os: macos,   i: macos-14,     cxx-std: 20, a: universal, t: macos-llvm,         tes: '',       g: Xcode,                 sh: bash,        name-suffix: '',               checks: false, osx-deployment-target: '10.9' }
          - { os: windows, i: ubuntu-22.04, cxx-std: 20, a: x86_64,    t: w64-mingw32,        tes: '-posix', g: Ninja Multi-Config,    sh: bash,        name-suffix: '',               checks: false, apt: mingw-w64 }
          - { os: windows, i: ubuntu-22.04, cxx-std: 20, a: i686,      t: w64-mingw32,        tes: '-posix', g: Ninja Multi-Config,    sh: bash,        name-suffix: '',               checks: false, apt: mingw-w64 }
          - { os: windows, i: windows-2022, cxx-std: 20, a: arm64,     t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', mt',           checks: false, msvc-mt: true }
          - { os: windows, i: windows-2022, cxx-std: 20, a: x86_64,    t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', mt',           checks: false, msvc-mt: true }
          - { os: windows, i: windows-2022, cxx-std: 20, a: i686,      t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', mt',           checks: false, msvc-mt: true }
          - { os: windows, i: windows-2022, cxx-std: 20, a: arm64,     t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', md',           checks: false, msvc-mt: false }
          - { os: windows, i: windows-2022, cxx-std: 20, a: x86_64,    t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', md',           checks: false, msvc-mt: false }
          - { os: windows, i: windows-2022, cxx-std: 20, a: i686,      t: windows-msvc,       tes: '',       g: Visual Studio 17 2022, sh: bash,        name-suffix: ', md',           checks: false, msvc-mt: false }
          - { os: windows, i: windows-2022, cxx-std: 20, a: x86_64,    t: msys2-gnu-ucrt64,   tes: '',       g: Ninja Multi-Config,    sh: 'msys2 {0}', name-suffix: ', UCRT64',       checks: false, msys: UCRT64 }
          - { os: windows, i: windows-2022, cxx-std: 20, a: x86_64,    t: msys2-llvm-clang64, tes: '',       g: Ninja Multi-Config,    sh: 'msys2 {0}', name-suffix: ', CLANG64',      checks: false, msys: CLANG64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/workflows/setup-env
        with:
          apt: ${{ matrix.apt }}
          msys: ${{ matrix.msys }}
          webkitgtk-api: ${{ matrix.webkitgtk-api }}

      - name: Build artifacts name
        uses: actions/github-script@v7
        id: artifacts-name
        env:
          OS: ${{ matrix.os }}
          IMAGE: ${{ matrix.i }}
          CXX_STD: ${{ matrix.cxx-std }}
          TOOLCHAIN: ${{ matrix.t }}
          TOOLCHAIN_EXECUTABLE_SUFFIX: ${{ matrix.tes }}
          WEBKITGTK_API: ${{ matrix.webkitgtk-api }}
          MSVC_MT: ${{ matrix.msvc-mt }}
        with:
          script: |
            return [
              process.env.OS,
              process.env.IMAGE,
              process.env.CXX_STD,
              process.env.TOOLCHAIN,
              process.env.TOOLCHAIN_EXECUTABLE_SUFFIX,
              process.env.WEBKITGTK_API,
              process.env.MSVC_MT,
            ].filter(v => v !== undefined && v !== "").join("_")

      - name: Build CMake options
        uses: actions/github-script@v7
        id: cmake-options
        env:
          ARCH: ${{ matrix.a }}
          CHECKS: ${{ matrix.checks }}
          DOCS: ${{ matrix.docs }}
          CXX_STD: ${{ matrix.cxx-std }}
          OSX_DEPLOYMENT_TARGET: ${{ matrix.osx-deployment-target }}
          TOOLCHAIN: ${{ matrix.t }}
          TOOLCHAIN_EXECUTABLE_SUFFIX: ${{ matrix.tes }}
          MSVC_MT: ${{ matrix.msvc-mt }}
        with:
          script: |
            const option = (k, v, t) => [k, ({
                Boolean: () => JSON.parse((v === undefined || v === "") ? false : v) ? "ON" : "OFF"
              }[t ? t.name : undefined] || (() => v))()
            ].join("=");
            return [
              option("CMAKE_CXX_STANDARD", process.env.CXX_STD),
              option("CMAKE_OSX_DEPLOYMENT_TARGET", process.env.OSX_DEPLOYMENT_TARGET),
              option("CMAKE_TOOLCHAIN_FILE", `cmake/toolchains/${process.env.ARCH}-${process.env.TOOLCHAIN}.cmake`),
              option("WEBVIEW_BUILD_DOCS", process.env.DOCS, Boolean),
              option("WEBVIEW_INSTALL_DOCS", process.env.DOCS, Boolean),
              option("WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX", process.env.TOOLCHAIN_EXECUTABLE_SUFFIX),
              option("WEBVIEW_USE_STATIC_MSVC_RUNTIME", process.env.MSVC_MT, Boolean),
              option("WEBVIEW_ENABLE_CHECKS", process.env.CHECKS, Boolean),
            ];

      - name: CMake
        uses: ./.github/workflows/cmake
        with:
          artifacts-name: ${{ steps.artifacts-name.outputs.result }}
          build-dir: build
          docs: ${{ matrix.docs }}
          docs-target: webview_docs
          cmake-options: ${{ steps.vars.outputs.cmake-options }}
          generator: ${{ matrix.g }}
          package: true
          package-source: ${{ matrix.package-source }}
          shell: ${{ matrix.sh }}
          source-dir: .
          test-wrapper-cmd: ${{ matrix.test-wrapper-cmd }}

  merge-package-artifacts:
    needs: package
    runs-on: ubuntu-22.04
    steps:
      - name: Merge package artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: package
          pattern: package_*
          delete-merged: true
